apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: aplicacion01
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: aplicacion01
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: ejemplo02
        image: xxxxx.dkr.ecr.us-east-1.amazonaws.com/ejemplo02:latest
        ports:
        - containerPort: 8080
